CC         = gcc
CFLAGS     = -Wall -Werror -std=gnu99
RM         = rm -f
EXECUTABLE = SBox
SOURCES    =  main.c Inglenook.c Inglenook.h Utils.h Utils.c

all: main.c 
	gcc $(CFLAGS) -o SBox $(SOURCES)

    clean: 
	$(RM) SBox

